name: one_cube

task_name: one_cube

image_shape: &image_shape [3, 84, 84]
shape_meta: &shape_meta # acceptable types: rgb, low_dim
  obs:
    # image:
    #     shape: *image_shape
    #     type: rgb
    point_cloud:
      shape: [1024, 3]
      type: point_cloud
    agent_pos:
      shape: [22]
      type: low_dim
  action:
    shape: [22]

# env_runner:
#   _target_: diffusion_policy_3d.env_runner.adroit_runner.OneCubeRunner
#   eval_episodes: 20
#   max_steps: 64
#   n_obs_steps: ${n_obs_steps}
#   n_action_steps: ${n_action_steps}
#   fps: 20
#   task_name: one_cube
#   render_size: 84
#   use_point_crop: ${policy.use_point_crop}

dataset:
  _target_: diffusion_policy_3d.dataset.one_cube_dataset.OneCubeDataset
  zarr_path: 
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
